import {
  Menu as MenuIcon,
  Visibility as VisibilityIcon,
  VisibilityOff as VisibilityOffIcon,
  Close as CloseIcon,
  ArrowBack as ArrowBackIcon,
  ChevronLeft as ChevronLeftIcon,
  ChevronRight as ChevronRightIcon,
  Home as HomeIcon,
  AccountCircle as ProfileIcon,
  AppRegistration as RegisterIcon,
  Login as LoginIcon,
  Logout as LogoutIcon,
  Bookmarks as BookmarksIcon,
  BookmarkAdd as BookmarkAddIcon,
  BookmarkAdded as BookmarkAddedIcon,
  Help as HelpIcon,
  Facebook as FacebookIcon,
  Instagram as InstagramIcon,
  Twitter as TwitterIcon,
  Reddit as RedditIcon,
  YouTube as YouTubeIcon,
} from '@mui/icons-material';

export {
  MenuIcon,
  VisibilityIcon,
  VisibilityOffIcon,
  CloseIcon,
  ArrowBackIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  HomeIcon,
  ProfileIcon,
  RegisterIcon,
  LoginIcon,
  LogoutIcon,
  BookmarksIcon,
  BookmarkAddIcon,
  BookmarkAddedIcon,
  HelpIcon,
  FacebookIcon,
  InstagramIcon,
  TwitterIcon,
  RedditIcon,
  YouTubeIcon,
};
